<a href="https://colab.research.google.com/github/AlishaJoy/NPL/blob/main/PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

In [8]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [11]:
ds = pd.read_csv('/content/sample_data/Amazon_Unlocked_Mobile.csv',engine ="python",error_bad_lines= False)
ds.head()

<ipython-input-11-42c30ac1cca5>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  ds = pd.read_csv('/content/sample_data/Amazon_Unlocked_Mobile.csv',engine ="python",error_bad_lines= False)


Product Name Brand Name   Price  \
0  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
1  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
2  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
3  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
4  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   

   Rating                                            Reviews  Review Votes  
0     5.0  I feel so LUCKY to have found this used (phone...           1.0  
1     4.0  nice phone, nice up grade from my pantach revu...           0.0  
2     5.0                                       Very pleased           0.0  
3     4.0  It works good but it goes slow sometimes but i...           0.0  
4     4.0  Great phone to replace my lost phone. The only...           0.0

In [12]:
# drop missing values:
ds.dropna(inplace= True)

In [13]:
# remove any 'neutral ratings equal to 3
ds = ds[ds['Rating']!=3]

In [15]:
# encode 4s and 5s as 1
#encode 1s and 2s as 0

ds['Positively Rated'] = np.where(ds['Rating']>3,1,0)
ds.head(10)

Product Name Brand Name   Price  \
0   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
1   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
2   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
3   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
4   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
5   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
6   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
7   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
8   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
11  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   

    Rating                                            Reviews  Review Votes  \
0      5.0  I feel so LUCKY to have found this used (phone...           1.0   
1      4.0  nice phone, nice up grade from my pantach revu...           0.0   
2      5.0                                       Very pleased           0.0   
3      4.0  It works good but it goes slow sometimes but i...           0.0   
4      4.0  Great phone to replace my lost phone. The only...           0.0   
5      1.0  I already had a phone with problems... I know ...           1.0   
6      2.0  The charging port was loose. I got that solder...           0.0   
7      2.0  Phone looks good but wouldn't stay charged, ha...           0.0   
8      5.0  I originally was using the Samsung S2 Galaxy f...           0.0   
11     5.0  This is a great product it came after two days...           0.0   

    Positively Rated  
0                  1  
1                  1  
2                  1  
3                  1  
4                  1  
5                  0  
6                  0  
7                  0  
8                  1  
11                 1

In [16]:
#most rating are positive
ds['Positively Rated'].mean()

0.7359845791485201

In [17]:
!pip install scikit_learn

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(ds['Reviews'],ds['Positively Rated'],random_state=0)
 #random_state=0 will maintain the random
 # x train = input
 # y train = label for the input


### CountVectorizer

In [35]:
li = ["welcome to this session","it starts at at nine","it ends at 4:30"]

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

In [63]:
#fit the countvectorizer to the training data
vect = CountVectorizer().fit(li)

In [38]:
vect.vocabulary_

{'welcome': 9,
 'to': 8,
 'this': 7,
 'session': 5,
 'it': 3,
 'starts': 6,
 'at': 1,
 'nine': 4,
 'ends': 2,
 '30': 0}

In [39]:
vect.transform(li).toarray() # each array is each sentence, each words repeatation

array([[0, 0, 0, 0, 0, 1, 0, 1, 1, 1],
       [0, 2, 0, 1, 1, 0, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0]])

In [71]:
vectt = CountVectorizer(ngram_range=(1,2)).fit(x_train)
vectt.vocabulary_

{'the': 441336,
 'smartphone': 408770,
 'did': 130667,
 'not': 299888,
 'meet': 272978,
 'my': 287288,
 'expectations': 157971,
 'camera': 87019,
 'does': 136757,
 'take': 432623,
 'pictures': 340238,
 'focused': 172373,
 'all': 24378,
 'photos': 339343,
 'are': 45178,
 'out': 323795,
 'of': 306297,
 'focus': 172284,
 'lost': 262116,
 'money': 281073,
 'disappointment': 134030,
 'want': 490900,
 'back': 55809,
 'bought': 75122,
 'when': 501040,
 'visiting': 488934,
 'in': 219156,
 'new': 294129,
 'york': 517898,
 'am': 28616,
 'now': 303793,
 'country': 114949,
 'is': 229945,
 'disaster': 134124,
 'the smartphone': 446580,
 'smartphone did': 408847,
 'did not': 130906,
 'not meet': 301123,
 'meet my': 272995,
 'my expectations': 288091,
 'expectations the': 158104,
 'the camera': 442424,
 'camera does': 87208,
 'does not': 136960,
 'not take': 301913,
 'take pictures': 432818,
 'pictures focused': 340333,
 'focused all': 172374,
 'all photos': 25097,
 'photos are': 339355,
 'are out': 

In [67]:
x_train_vectorized = vectt.transform(x_train)
x_train_vectorized

<135012x521406 sparse matrix of type '<class 'numpy.int64'>'
	with 7628875 stored elements in Compressed Sparse Row format>

In [68]:
from sklearn.linear_model import LogisticRegression

In [69]:
model = LogisticRegression()
model.fit(x_train_vectorized,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [47]:
predictions = model.predict(vectt.transform(x_test))

In [48]:
predictions

array([0, 0, 1, ..., 1, 1, 0])

In [49]:
from sklearn.metrics import roc_auc_score
print('AUC:',roc_auc_score(y_test,predictions))

AUC: 0.9281218851117281


In [61]:
print(model.predict(vectt.transform(['very pleased','not an issue,phone is working','amazing','smelly','good','loved it'])))

[1 0 1 1 1 1]


In [72]:
# make function to map the 0 and 1 as positive and negative